### ISSUE TITLE
Admin deep links

### ISSUE THREAD

**Issue by roborourke** [humanmade/platform-documentation#25]
As well as linking to documentation across modules it'd be handy to have the ability to link to sections of the admin when the docs are being viewed in the admin.

Outside of the admin context the links could be output as plain text.

Example:

```md
# Some cool feature

This cool feature can be managed through the 
[CMS admin](/wp-admin/edit.php?post_type=blah) 
and lets you create AI powered VR experiences for 
selecting emoji.
```

**Comment by rmccue** [comment]
I'm thinking we add an `internal://` scheme to link to various things on the site.

* `internal://home/foo` -> `home_url( 'foo' )`
* `internal://site/foo` -> `site_url( 'foo' )`
* `internal://admin/foo` -> `admin_url( 'foo' )`
* `internal://network-admin/foo` -> `network_admin_url( 'foo' )`

It'd be useful to be able to have `internal://rest-api/` as well, but we'd want that substituted into the content rather than as a link. We can explore that separately I think.

**Comment by rmccue** [comment]
Also, on the public documentation, we can have these return `null` and remove the link for now.

When we have time, we can change this to have the user select a site for the URLs based on their account.
